#####################################################################################################################
# github-host           => GitHub url for checking pull requests
# github-bearer-token   => Bearer token to access GitHub (Set as environment variable on this name)
# type                  => Type of channel to send the notification [Teams, Slack, Raw (default)]
# avatar                => Image to send on notification
# channel               => channel url should be setup as an Environment Variable with this name
# repositories -> name  => repository name to check pull requests
#####################################################################################################################
author : Ruwan Mettananda
github-bearer-token: github_bearer_token
default-channel_type: Teams
default-channel: default_channel
default-avatar: https://image.flaticon.com/icons/png/512/5147/5147107.png
repositories:
  - name: ansible-terraform
    owner: ruwanvm
    channel_type: slack
    channel: slack-channel
notifications:
  pull-open-days: 3